### ISSUE TITLE
**suggestion:** Consider using a configuration object for settings

### ISSUE THREAD

**Issue by yingbull** [ClinicianFOCUS/FreeScribe#10]
**suggestion:** Consider using a configuration object for settings

The save_settings method has many parameters. Consider using a configuration object to encapsulate these settings, which would make the method signature cleaner and more maintainable.

```
class SettingsConfig:
    def __init__(self, koboldcpp_ip, whisperaudio_ip, openai_api_key, aiscribe_text, aiscribe2_text, settings_window,
                 koboldcpp_port, whisperaudio_port, ssl_enable, ssl_selfcert, api_style):
        self.koboldcpp_ip = koboldcpp_ip
        self.whisperaudio_ip = whisperaudio_ip
        self.openai_api_key = openai_api_key
        self.aiscribe_text = aiscribe_text
        self.aiscribe2_text = aiscribe2_text
        self.settings_window = settings_window
        self.koboldcpp_port = koboldcpp_port
        self.whisperaudio_port = whisperaudio_port
        self.ssl_enable = ssl_enable
        self.ssl_selfcert = ssl_selfcert
        self.api_style = api_style

def save_settings(self, config: SettingsConfig):
```

_Originally posted by @sourcery-ai[bot] in https://github.com/ClinicianFOCUS/FreeScribe/pull/6#discussion_r1801929896_

**Comment by ItsSimko** [comment]
Not really needed as we store most of these in a json table now and then load an unload that and only 2 of those variables still exist and could still be easily removed.
