### ISSUE TITLE
Relative is OK for our use as the installer will bundle it all to the same folder. Let me know if changes should be made? Possibly pass the install path from the installer to the client and eventually adjust paths based on that. Open issue?

### ISSUE THREAD

**Issue by yingbull** [ClinicianFOCUS/FreeScribe#36]
Relative is OK for our use as the installer will bundle it all to the same folder. Let me know if changes should be made? Possibly pass the install path from the installer to the client and eventually adjust paths based on that. Open issue?

_Originally posted by @ItsSimko in https://github.com/ClinicianFOCUS/FreeScribe/pull/33#discussion_r1825027209_
Teaching for backlog

**Comment by ItsSimko** [comment]
pemba bundled directly into the exe. not needed.
